2025-03-04 01:24:29,588 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-03-04 01:27:15,298 - fastapi - INFO - User: Anonymous | Request: GET http://127.0.0.1:8000/
2025-03-04 01:27:15,300 - fastapi - INFO - Response: 200 | Time taken: 0.0025 sec
2025-03-04 01:32:06,204 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 01:32:06,217 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-03-04 01:32:06,394 - fastapi - INFO - Response: 200 | Time taken: 0.1901 sec
2025-03-04 01:32:34,986 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/
2025-03-04 01:32:34,987 - fastapi - INFO - Response: 200 | Time taken: 0.0006 sec
2025-03-04 01:32:53,085 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 01:32:53,250 - fastapi - INFO - Response: 200 | Time taken: 0.1652 sec
2025-03-04 01:34:58,269 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/auth/login
2025-03-04 01:34:58,270 - fastapi - INFO - Response: 405 | Time taken: 0.0005 sec
2025-03-04 01:44:33,559 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 01:44:33,724 - fastapi - INFO - Response: 200 | Time taken: 0.1652 sec
2025-03-04 01:44:34,169 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 01:44:34,334 - fastapi - INFO - Response: 200 | Time taken: 0.1651 sec
2025-03-04 01:44:34,779 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 01:44:34,943 - fastapi - INFO - Response: 200 | Time taken: 0.1644 sec
2025-03-04 01:44:35,371 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 01:44:35,536 - fastapi - INFO - Response: 200 | Time taken: 0.1650 sec
2025-03-04 01:44:35,951 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 01:44:36,115 - fastapi - INFO - Response: 200 | Time taken: 0.1644 sec
2025-03-04 01:44:36,513 - fastapi - WARNING - Rate limit exceeded for IP: 127.0.0.1
2025-03-04 01:44:38,066 - fastapi - WARNING - Rate limit exceeded for IP: 127.0.0.1
2025-03-04 01:44:38,874 - fastapi - WARNING - Rate limit exceeded for IP: 127.0.0.1
2025-03-04 01:44:39,804 - fastapi - WARNING - Rate limit exceeded for IP: 127.0.0.1
2025-03-04 01:52:08,630 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 01:52:08,795 - fastapi - INFO - Response: 200 | Time taken: 0.1649 sec
2025-03-04 01:52:09,612 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 01:52:09,777 - fastapi - INFO - Response: 200 | Time taken: 0.1648 sec
2025-03-04 01:52:10,353 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 01:52:10,518 - fastapi - INFO - Response: 200 | Time taken: 0.1645 sec
2025-03-04 01:52:10,974 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 01:52:11,138 - fastapi - INFO - Response: 200 | Time taken: 0.1646 sec
2025-03-04 01:52:11,526 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 01:52:11,691 - fastapi - INFO - Response: 200 | Time taken: 0.1651 sec
2025-03-04 01:52:12,126 - fastapi - WARNING - Rate limit exceeded for IP: 127.0.0.1
2025-03-04 01:52:12,919 - fastapi - WARNING - Rate limit exceeded for IP: 127.0.0.1
2025-03-04 01:52:13,546 - fastapi - WARNING - Rate limit exceeded for IP: 127.0.0.1
2025-03-04 01:53:47,697 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/
2025-03-04 01:53:47,699 - fastapi - INFO - Response: 200 | Time taken: 0.0026 sec
2025-03-04 01:53:55,366 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 01:53:55,381 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-03-04 01:53:55,558 - fastapi - INFO - Response: 200 | Time taken: 0.1924 sec
2025-03-04 01:53:57,039 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 01:53:57,203 - fastapi - INFO - Response: 200 | Time taken: 0.1647 sec
2025-03-04 01:53:57,786 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 01:53:57,952 - fastapi - INFO - Response: 200 | Time taken: 0.1662 sec
2025-03-04 01:53:58,503 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 01:53:58,668 - fastapi - INFO - Response: 200 | Time taken: 0.1652 sec
2025-03-04 01:53:59,137 - fastapi - WARNING - Rate limit exceeded for IP: 127.0.0.1
2025-03-04 01:53:59,809 - fastapi - WARNING - Rate limit exceeded for IP: 127.0.0.1
2025-03-04 01:54:00,353 - fastapi - WARNING - Rate limit exceeded for IP: 127.0.0.1
2025-03-04 02:33:59,195 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/
2025-03-04 02:33:59,198 - fastapi - INFO - Response: 200 | Time taken: 0.0026 sec
2025-03-04 02:34:12,470 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 02:34:12,470 - fastapi - INFO - Response: 404 | Time taken: 0.0005 sec
2025-03-04 02:34:18,247 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 02:34:18,247 - fastapi - INFO - Response: 404 | Time taken: 0.0004 sec
2025-03-04 02:36:16,159 - fastapi - INFO - User: Anonymous | Request: GET http://127.0.0.1:8000/
2025-03-04 02:36:16,160 - fastapi - INFO - Response: 200 | Time taken: 0.0008 sec
2025-03-04 02:38:24,079 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 02:38:24,079 - fastapi - INFO - Response: 404 | Time taken: 0.0005 sec
2025-03-04 02:38:36,076 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 02:38:36,090 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-03-04 02:38:36,269 - fastapi - INFO - Response: 200 | Time taken: 0.1930 sec
2025-03-04 02:41:39,803 - fastapi - INFO - User: test@ting.com | Request: GET http://localhost:8000/users/me
2025-03-04 02:41:39,820 - fastapi - INFO - Response: 200 | Time taken: 0.0164 sec
2025-03-04 02:45:07,100 - fastapi - WARNING - Invalid token detected for request: http://localhost:8000/users/me
2025-03-04 02:45:07,100 - fastapi - INFO - Unauthenticated access attempt to http://localhost:8000/users/me
2025-03-04 02:54:51,936 - fastapi - INFO - DB URL fetched from .env file
2025-03-04 02:55:05,255 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/
2025-03-04 02:55:05,257 - fastapi - INFO - Response: 200 | Time taken: 0.0026 sec
2025-03-04 03:39:25,503 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/
2025-03-04 03:39:25,524 - fastapi - INFO - Response: 200 | Time taken: 0.0207 sec
2025-03-04 03:39:26,112 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/
2025-03-04 03:39:26,113 - fastapi - INFO - Response: 200 | Time taken: 0.0006 sec
2025-03-04 03:40:52,010 - fastapi - INFO - DB URL fetched from .env file
2025-03-04 03:40:59,412 - fastapi - INFO - DB URL fetched from .env file
2025-03-04 13:52:25,399 - fastapi - INFO - DB URL fetched from .env file
2025-03-04 13:52:26,895 - fastapi - INFO - DB URL fetched from .env file
2025-03-04 13:52:26,968 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:27,319 - watchfiles.main - INFO - 4 changes detected
2025-03-04 13:52:27,669 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:28,020 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:28,370 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:28,721 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:29,071 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:29,422 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:29,772 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:30,123 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:30,473 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:30,824 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:31,174 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:31,525 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:31,875 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:32,226 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:32,576 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:32,927 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:33,277 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:33,627 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:33,978 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:34,328 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:34,679 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:35,029 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:35,380 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:35,730 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:36,081 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:36,431 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:36,781 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:37,132 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:37,482 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:37,833 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:38,184 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:38,534 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:38,884 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:39,235 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:39,585 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:39,936 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:40,286 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:40,637 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:40,987 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:41,338 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:41,688 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:42,039 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:42,389 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:42,740 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:43,090 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:43,441 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:43,791 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:44,141 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:44,492 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:44,842 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:45,193 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:45,543 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:45,894 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:46,244 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:46,595 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:46,945 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:47,296 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:47,646 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:47,997 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:48,347 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:48,698 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:49,048 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:49,398 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:49,749 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:50,099 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:50,450 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:50,800 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:51,151 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:51,501 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:51,852 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:52,202 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:52,553 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:52,903 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:53,254 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:53,604 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:53,954 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:54,305 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:54,655 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:55,006 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:55,356 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:55,707 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:56,057 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:56,408 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:56,758 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:57,108 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:57,459 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:57,810 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:58,160 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:58,511 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:58,861 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:59,211 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:59,562 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:52:59,912 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:00,263 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:00,613 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:00,964 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:01,314 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:01,665 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:02,015 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:02,366 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:02,716 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:03,067 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:03,417 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:03,768 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:04,118 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:04,468 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:04,819 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:05,169 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:05,520 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:05,870 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:06,221 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:06,571 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:06,922 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:07,272 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:07,623 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:07,973 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:08,324 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:08,674 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:09,025 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:09,375 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:09,726 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:10,076 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:10,426 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:10,777 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:11,127 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:11,478 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:11,828 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:12,179 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:12,530 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:12,880 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:13,231 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:13,581 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:13,931 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:14,282 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:14,632 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:14,983 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:15,333 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:15,684 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:16,035 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:16,385 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:16,735 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:17,086 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:17,436 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:17,787 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:18,137 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:18,488 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:18,838 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:19,189 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:19,539 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:19,890 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:20,240 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:20,591 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:20,941 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:21,292 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:21,642 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:21,992 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:22,343 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:22,693 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:23,044 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:23,394 - watchfiles.main - INFO - 1 change detected
2025-03-04 13:53:47,357 - fastapi - INFO - DB URL fetched from .env file
2025-03-04 13:53:59,857 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/
2025-03-04 13:53:59,868 - fastapi - INFO - Response: 200 | Time taken: 0.0109 sec
2025-03-04 13:54:00,039 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/favicon.ico
2025-03-04 13:54:00,040 - fastapi - INFO - Response: 404 | Time taken: 0.0004 sec
2025-03-04 13:54:07,115 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/register
2025-03-04 14:00:48,979 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/register
2025-03-04 14:00:49,561 - fastapi - INFO - Response: 400 | Time taken: 0.5823 sec
2025-03-04 14:01:24,669 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 14:01:24,672 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-03-04 14:01:24,866 - fastapi - INFO - Response: 400 | Time taken: 0.1971 sec
2025-03-04 14:08:16,035 - fastapi - INFO - Unauthenticated access attempt to http://localhost:8000/users/me
2025-03-04 14:08:16,056 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/auth/login
2025-03-04 14:08:16,056 - fastapi - INFO - Response: 405 | Time taken: 0.0002 sec
2025-03-04 14:08:25,453 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 14:08:25,694 - fastapi - INFO - Response: 200 | Time taken: 0.2418 sec
2025-03-04 14:08:30,786 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/auth/me
2025-03-04 14:08:30,786 - fastapi - INFO - Response: 404 | Time taken: 0.0004 sec
2025-03-04 14:17:15,684 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 14:17:15,850 - fastapi - INFO - Response: 200 | Time taken: 0.1662 sec
2025-03-04 14:17:41,925 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/user
2025-03-04 14:17:41,925 - fastapi - INFO - Response: 404 | Time taken: 0.0004 sec
2025-03-04 14:17:46,006 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/user/me
2025-03-04 14:17:46,007 - fastapi - INFO - Response: 404 | Time taken: 0.0004 sec
2025-03-04 14:17:53,026 - fastapi - INFO - Unauthenticated access attempt to http://localhost:8000/users/me
2025-03-04 14:17:53,033 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/auth/login
2025-03-04 14:17:53,034 - fastapi - INFO - Response: 405 | Time taken: 0.0002 sec
2025-03-04 14:19:50,713 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 14:19:50,877 - fastapi - INFO - Response: 200 | Time taken: 0.1643 sec
2025-03-04 14:20:14,992 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 14:20:15,156 - fastapi - INFO - Response: 200 | Time taken: 0.1647 sec
2025-03-04 14:20:23,236 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/auth/login
2025-03-04 14:20:23,236 - fastapi - INFO - Response: 405 | Time taken: 0.0003 sec
2025-03-04 14:20:48,951 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/user/me
2025-03-04 14:20:48,951 - fastapi - INFO - Response: 404 | Time taken: 0.0004 sec
2025-03-04 14:21:18,233 - fastapi - WARNING - Invalid token detected for request: http://localhost:8000/users/me
2025-03-04 14:21:18,233 - fastapi - INFO - Unauthenticated access attempt to http://localhost:8000/users/me
2025-03-04 14:21:27,340 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 14:21:27,505 - fastapi - INFO - Response: 200 | Time taken: 0.1650 sec
2025-03-04 14:22:02,085 - fastapi - INFO - User: test@ting.com | Request: GET http://localhost:8000/users/me
2025-03-04 14:22:02,087 - fastapi - INFO - Response: 200 | Time taken: 0.0024 sec
2025-03-04 14:26:59,829 - fastapi - INFO - DB URL fetched from .env file
2025-03-04 14:27:06,336 - fastapi - INFO - User: test@ting.com | Request: GET http://localhost:8000/users/me
2025-03-04 14:27:06,355 - routes.users - INFO - USER Validation Complete
2025-03-04 14:27:06,355 - routes.users - INFO - User valid
2025-03-04 14:27:06,358 - fastapi - INFO - Response: 200 | Time taken: 0.0231 sec
2025-03-04 14:29:50,705 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 14:29:50,707 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-03-04 14:29:50,885 - fastapi - INFO - Response: 200 | Time taken: 0.1799 sec
2025-03-04 14:30:27,244 - fastapi - INFO - User: test@ting.com | Request: GET http://localhost:8000/users/me
2025-03-04 14:30:27,246 - routes.users - INFO - USER Validation Complete
2025-03-04 14:30:27,246 - routes.users - INFO - User valid
2025-03-04 14:30:27,247 - fastapi - INFO - Response: 200 | Time taken: 0.0027 sec
2025-03-04 14:31:02,308 - fastapi - WARNING - Invalid token detected for request: http://localhost:8000/users/me
2025-03-04 14:31:02,308 - fastapi - INFO - Unauthenticated access attempt to http://localhost:8000/users/me
2025-03-04 15:47:42,201 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/
2025-03-04 15:47:42,203 - fastapi - INFO - Response: 200 | Time taken: 0.0024 sec
2025-03-04 15:47:47,711 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 15:47:47,731 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-03-04 15:47:47,910 - fastapi - INFO - Response: 200 | Time taken: 0.1984 sec
2025-03-04 15:48:33,896 - fastapi - INFO - User: test@ting.com | Request: GET http://localhost:8000/users/me
2025-03-04 15:48:33,897 - routes.users - INFO - User validated via /me endpoint.
2025-03-04 15:48:33,901 - fastapi - INFO - Response: 200 | Time taken: 0.0051 sec
2025-03-04 15:49:06,640 - fastapi - INFO - User: test@ting.com | Request: GET http://localhost:8000/users/dashboard
2025-03-04 15:49:06,641 - fastapi - INFO - Response: 200 | Time taken: 0.0021 sec
2025-03-04 15:50:21,544 - fastapi - INFO - User: test@ting.com | Request: GET http://localhost:8000/users/dashboard
2025-03-04 15:50:21,546 - fastapi - INFO - Response: 200 | Time taken: 0.0021 sec
2025-03-04 15:50:26,356 - fastapi - INFO - User: test@ting.com | Request: GET http://localhost:8000/users/dashboard
2025-03-04 15:50:26,358 - fastapi - INFO - Response: 200 | Time taken: 0.0021 sec
2025-03-04 15:54:01,265 - fastapi - INFO - User: test@ting.com | Request: GET http://localhost:8000/users/dashboard
2025-03-04 15:54:01,267 - fastapi - INFO - Response: 200 | Time taken: 0.0020 sec
2025-03-04 15:54:06,522 - fastapi - WARNING - Invalid token detected for request: http://localhost:8000/users/me
2025-03-04 15:54:06,522 - fastapi - INFO - Unauthenticated access attempt to http://localhost:8000/users/me
2025-03-04 15:56:48,223 - fastapi - WARNING - Invalid token detected for request: http://localhost:8000/users/me
2025-03-04 15:56:48,223 - fastapi - INFO - Unauthenticated access attempt to http://localhost:8000/users/me
2025-03-04 15:57:00,641 - fastapi - WARNING - Invalid token detected for request: http://localhost:8000/users/me
2025-03-04 15:57:00,641 - fastapi - INFO - Unauthenticated access attempt to http://localhost:8000/users/me
2025-03-04 15:57:21,886 - fastapi - WARNING - Invalid token detected for request: http://localhost:8000/users/me
2025-03-04 15:57:21,886 - fastapi - INFO - Unauthenticated access attempt to http://localhost:8000/users/me
2025-03-04 15:57:38,999 - fastapi - WARNING - Invalid token detected for request: http://localhost:8000/users/me
2025-03-04 15:57:38,999 - fastapi - INFO - Unauthenticated access attempt to http://localhost:8000/users/me
2025-03-04 15:58:08,070 - fastapi - WARNING - Invalid token detected for request: http://localhost:8000/users/me
2025-03-04 15:58:08,070 - fastapi - INFO - Unauthenticated access attempt to http://localhost:8000/users/me
2025-03-04 15:58:08,070 - fastapi - WARNING - Invalid token detected for request: http://localhost:8000/auth/login
2025-03-04 15:58:08,070 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/auth/login
2025-03-04 15:58:08,071 - fastapi - INFO - Response: 405 | Time taken: 0.0005 sec
2025-03-04 15:59:04,172 - fastapi - WARNING - Invalid token detected for request: http://localhost:8000/users/me
2025-03-04 15:59:04,172 - fastapi - INFO - Unauthenticated access attempt to http://localhost:8000/users/me
2025-03-04 16:06:29,421 - fastapi - INFO - User: test@ting.com | Request: GET http://localhost:8000/users/dashboard
2025-03-04 16:06:29,421 - routes.users - INFO - Got email from request
2025-03-04 16:06:29,440 - fastapi - INFO - Response: 200 | Time taken: 0.0211 sec
2025-03-04 16:07:56,829 - fastapi - INFO - User: test@ting.com | Request: GET http://localhost:8000/users/dashboard
2025-03-04 16:07:56,830 - routes.users - INFO - Got email from request
2025-03-04 16:07:56,831 - fastapi - INFO - Response: 200 | Time taken: 0.0021 sec
2025-03-04 16:10:58,225 - fastapi - INFO - User: test@ting.com | Request: GET http://localhost:8000/users/dashboard
2025-03-04 16:10:58,226 - routes.users - INFO - Got email from request
2025-03-04 16:10:58,350 - routes.users - INFO - TEST: Folios is []
2025-03-04 16:10:58,351 - fastapi - INFO - Response: 200 | Time taken: 0.1265 sec
2025-03-04 16:13:56,324 - fastapi - INFO - User: test@ting.com | Request: GET http://localhost:8000/users/dashboard
2025-03-04 16:13:56,325 - routes.users - INFO - Got email from request
2025-03-04 16:13:56,344 - routes.users - INFO - User folio record not found; redirecting to /users/getstarted
2025-03-04 16:13:56,345 - fastapi - INFO - Response: 307 | Time taken: 0.0218 sec
2025-03-04 16:13:56,346 - fastapi - INFO - User: test@ting.com | Request: GET http://localhost:8000/users/getstarted
2025-03-04 16:13:56,347 - fastapi - INFO - Response: 200 | Time taken: 0.0005 sec
2025-03-04 16:23:40,377 - fastapi - INFO - Unauthenticated access attempt to http://localhost:8000/users/dashboard
2025-03-04 16:23:40,398 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/auth/login
2025-03-04 16:23:40,398 - fastapi - INFO - Response: 405 | Time taken: 0.0003 sec
2025-03-04 16:26:36,060 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/upload
2025-03-04 16:26:36,060 - fastapi - INFO - Response: 404 | Time taken: 0.0005 sec
2025-03-04 16:27:16,573 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/
2025-03-04 16:27:16,576 - fastapi - INFO - Response: 200 | Time taken: 0.0028 sec
2025-03-04 16:27:18,868 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/
2025-03-04 16:27:18,868 - fastapi - INFO - Response: 200 | Time taken: 0.0006 sec
2025-03-04 16:27:54,163 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/upload
2025-03-04 16:27:54,165 - fastapi - INFO - Response: 200 | Time taken: 0.0021 sec
2025-03-04 16:36:32,566 - fastapi - WARNING - Invalid token detected for request: http://localhost:8000/users/dashboard
2025-03-04 16:36:32,566 - fastapi - INFO - Unauthenticated access attempt to http://localhost:8000/users/dashboard
2025-03-04 16:37:51,319 - fastapi - WARNING - Invalid token detected for request: http://localhost:8000/users/dashboard
2025-03-04 16:37:51,319 - fastapi - INFO - Unauthenticated access attempt to http://localhost:8000/users/dashboard
2025-03-04 16:46:28,966 - fastapi - WARNING - Invalid token detected for request: http://localhost:8000/users/dashboard
2025-03-04 16:46:28,966 - fastapi - INFO - Unauthenticated access attempt to http://localhost:8000/users/dashboard
2025-03-04 16:50:20,440 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/upload
2025-03-04 16:50:20,442 - fastapi - INFO - Response: 200 | Time taken: 0.0020 sec
2025-03-04 16:50:33,369 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/upload.py
2025-03-04 16:50:33,369 - fastapi - INFO - Response: 404 | Time taken: 0.0006 sec
2025-03-04 16:52:21,208 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/upload.py
2025-03-04 16:52:21,208 - fastapi - INFO - Response: 404 | Time taken: 0.0004 sec
2025-03-04 17:01:14,795 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/upload
2025-03-04 17:01:14,797 - fastapi - INFO - Response: 200 | Time taken: 0.0021 sec
2025-03-04 17:01:24,750 - fastapi - INFO - Unauthenticated access attempt to http://localhost:8000/users/getstarted
2025-03-04 17:01:24,836 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-04 17:01:24,857 - fastapi - INFO - Response: 422 | Time taken: 0.0209 sec
2025-03-04 21:17:07,046 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/
2025-03-04 21:17:07,048 - fastapi - INFO - Response: 200 | Time taken: 0.0021 sec
2025-03-04 21:17:07,171 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/favicon.ico
2025-03-04 21:17:07,171 - fastapi - INFO - Response: 404 | Time taken: 0.0003 sec
2025-03-04 21:17:12,142 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/upload
2025-03-04 21:17:12,143 - fastapi - INFO - Response: 200 | Time taken: 0.0010 sec
2025-03-04 21:17:28,312 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-04 21:17:28,372 - root - INFO - Received file '13.pdf' with provided password.
2025-03-04 21:26:41,642 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-04 21:26:41,677 - root - INFO - Received file '13.pdf' with provided password.
2025-03-04 21:26:56,605 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-04 21:26:56,655 - root - INFO - Received file '13.pdf' with provided password.
2025-03-04 21:26:56,655 - fastapi - INFO - Response: 200 | Time taken: 0.0501 sec
2025-03-04 21:34:25,766 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-04 21:34:25,824 - root - INFO - Received file '13.pdf' with provided password.
2025-03-04 21:34:46,279 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-04 21:34:46,339 - root - INFO - Received file '13.pdf' with provided password.
2025-03-04 21:34:51,409 - fastapi - INFO - Response: 200 | Time taken: 5.1298 sec
2025-03-04 21:36:42,730 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-04 21:36:42,758 - root - INFO - Received file '13.pdf' with provided password.
2025-03-04 21:37:26,046 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-04 21:37:26,116 - root - INFO - Received file '13.pdf' with provided password.
2025-03-04 21:38:30,662 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-04 21:38:30,730 - root - INFO - Received file '13.pdf' with provided password.
2025-03-04 21:38:35,098 - fastapi - INFO - Response: 200 | Time taken: 4.4357 sec
2025-03-04 21:38:49,036 - fastapi - INFO - User: Anonymous | Request: GET http://172.16.16.40:8000/dashboard
2025-03-04 21:38:49,036 - fastapi - INFO - Response: 404 | Time taken: 0.0004 sec
2025-03-04 21:38:49,130 - fastapi - INFO - User: Anonymous | Request: GET http://172.16.16.40:8000/favicon.ico
2025-03-04 21:38:49,130 - fastapi - INFO - Response: 404 | Time taken: 0.0003 sec
2025-03-04 21:38:51,936 - fastapi - INFO - User: Anonymous | Request: GET http://172.16.16.40:8000/
2025-03-04 21:38:51,938 - fastapi - INFO - Response: 200 | Time taken: 0.0022 sec
2025-03-04 21:38:55,428 - fastapi - INFO - User: Anonymous | Request: GET http://172.16.16.40:8000/upload
2025-03-04 21:38:55,429 - fastapi - INFO - Response: 200 | Time taken: 0.0011 sec
2025-03-04 21:45:55,523 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/upload
2025-03-04 21:45:55,523 - fastapi - INFO - Response: 200 | Time taken: 0.0005 sec
2025-03-04 21:46:08,842 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-04 21:46:08,901 - root - INFO - Received file '13.pdf' with provided password.
2025-03-04 21:46:13,227 - fastapi - INFO - Response: 200 | Time taken: 4.3850 sec
2025-03-04 21:47:44,941 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-04 21:47:44,996 - root - INFO - Received file '13.pdf' with provided password.
2025-03-04 21:47:47,225 - fastapi - INFO - Response: 200 | Time taken: 2.2845 sec
2025-03-04 21:50:06,394 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-04 21:50:06,439 - root - INFO - Received file '13.pdf' with provided password.
2025-03-04 21:50:08,671 - fastapi - INFO - Response: 200 | Time taken: 2.2769 sec
2025-03-05 11:43:17,277 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-05 11:43:17,302 - root - INFO - Received file '13.pdf' with provided password.
2025-03-05 11:43:17,302 - routes.pdf_converter - INFO - Converting /home/panda/mfa/financial-decision/upload/13.pdf to json
2025-03-05 11:43:19,562 - routes.pdf_converter - INFO - File Converted
2025-03-05 11:43:19,562 - fastapi - INFO - Response: 200 | Time taken: 2.2847 sec
2025-03-05 11:45:14,178 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-05 11:45:14,201 - root - INFO - Received file '13.pdf' with provided password.
2025-03-05 11:45:14,201 - fastapi - INFO - Response: 200 | Time taken: 0.0236 sec
2025-03-05 11:48:37,283 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-05 11:48:37,347 - root - INFO - Received file '13.pdf' with provided password.
2025-03-05 11:48:37,364 - routes.pdf_converter - ERROR - Conversion PARSER Module FAILED. Is password Correct? Incorrect PDF password!
Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/casparser/parsers/pdfminer.py", line 133, in cas_pdf_to_text
    document = PDFDocument(pdf_parser, password=password)
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/pdfminer/pdfdocument.py", line 744, in __init__
    self._initialize_password(password)
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/pdfminer/pdfdocument.py", line 771, in _initialize_password
    handler = factory(docid, param, password)
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/pdfminer/pdfdocument.py", line 358, in __init__
    self.init()
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/pdfminer/pdfdocument.py", line 366, in init
    self.init_key()
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/pdfminer/pdfdocument.py", line 381, in init_key
    raise PDFPasswordIncorrect
pdfminer.pdfdocument.PDFPasswordIncorrect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/routes/pdf_converter.py", line 37, in convertpdf
    csv_str = casparser.read_cas_pdf(pdf_file_path, password, output="json")
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/casparser/parsers/__init__.py", line 34, in read_cas_pdf
    partial_cas_data = cas_pdf_to_text(filename, password)
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/casparser/parsers/pdfminer.py", line 135, in cas_pdf_to_text
    raise IncorrectPasswordError("Incorrect PDF password!")
casparser.exceptions.IncorrectPasswordError: Incorrect PDF password!
2025-03-05 11:48:37,364 - fastapi - INFO - Response: 200 | Time taken: 0.0816 sec
2025-03-05 11:53:57,330 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-05 11:53:57,380 - root - INFO - Received file '13.pdf' with provided password.
2025-03-05 11:53:57,396 - routes.pdf_converter - ERROR - Conversion PARSER Module FAILED. Incorrect PDF password!
2025-03-05 11:53:57,396 - fastapi - INFO - Response: 200 | Time taken: 0.0661 sec
2025-03-05 12:05:34,878 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-05 12:05:34,883 - root - INFO - Received file '13.pdf' with provided password.
2025-03-05 12:05:37,090 - routes.pdf_converter - INFO - File Converted
2025-03-05 12:05:37,091 - fastapi - INFO - Response: 200 | Time taken: 2.2126 sec
2025-03-05 12:06:51,297 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-05 12:06:51,346 - root - INFO - Received file '13.pdf' with provided password.
2025-03-05 12:06:53,575 - routes.pdf_converter - INFO - File Converted
2025-03-05 12:06:53,575 - routes.pdf_converter - INFO - Valid JSON
2025-03-05 12:06:53,575 - fastapi - INFO - Response: 200 | Time taken: 2.2781 sec
2025-03-06 11:41:50,664 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/
2025-03-06 11:41:50,729 - fastapi - INFO - Response: 200 | Time taken: 0.0650 sec
2025-03-06 11:41:57,179 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/upload
2025-03-06 11:41:57,194 - fastapi - INFO - Response: 200 | Time taken: 0.0156 sec
2025-03-06 11:42:26,526 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-06 11:42:26,572 - root - INFO - Received file '13.pdf' with provided password.
2025-03-06 11:42:26,572 - routes.pdf_converter - INFO - File Conversion START
2025-03-06 11:42:29,458 - routes.pdf_converter - INFO - File Conversion FINISH
2025-03-06 11:42:29,482 - routes.pdf_converter - ERROR - Error publishing JSON to DB, Exception: Date format for '01-Jan-1985' not recognized.
Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/routes/pdf_converter.py", line 48, in publish_json_to_db
    sp_from = parse_date(sp_data.get("from"))
  File "/home/panda/mfa/financial-decision/routes/pdf_converter.py", line 40, in parse_date
    raise ValueError(f"Date format for '{date_str}' not recognized.")
ValueError: Date format for '01-Jan-1985' not recognized.
2025-03-06 11:42:29,483 - fastapi - INFO - Response: 200 | Time taken: 2.9567 sec
2025-03-06 11:47:02,813 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-06 11:47:02,900 - root - INFO - Received file '13.pdf' with provided password.
2025-03-06 11:47:02,900 - routes.pdf_converter - INFO - File Conversion START
2025-03-06 11:47:05,130 - routes.pdf_converter - INFO - File Conversion FINISH
2025-03-06 11:47:05,131 - routes.pdf_converter - ERROR - Error publishing JSON to DB, Exception: Date format for '01-Jan-1985' not recognized.
Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/routes/pdf_converter.py", line 48, in publish_json_to_db
    sp_from = parse_date(sp_data.get("from"))
  File "/home/panda/mfa/financial-decision/routes/pdf_converter.py", line 40, in parse_date
    raise ValueError(f"Date format for '{date_str}' not recognized.")
ValueError: Date format for '01-Jan-1985' not recognized.
2025-03-06 11:47:05,132 - fastapi - INFO - Response: 200 | Time taken: 2.3185 sec
2025-03-06 11:47:30,966 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-06 11:47:31,001 - root - INFO - Received file '13.pdf' with provided password.
2025-03-06 11:47:31,001 - routes.pdf_converter - INFO - File Conversion START
2025-03-06 11:47:33,267 - routes.pdf_converter - INFO - File Conversion FINISH
2025-03-06 11:47:33,268 - routes.pdf_converter - ERROR - Error publishing JSON to DB, Exception: Date format for '01-Jan-1985' not recognized.
2025-03-06 11:47:33,268 - fastapi - INFO - Response: 200 | Time taken: 2.3028 sec
2025-03-06 11:48:48,804 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-06 11:48:48,829 - root - INFO - Received file '13.pdf' with provided password.
2025-03-06 11:48:48,829 - routes.pdf_converter - INFO - File Conversion START
2025-03-06 11:48:51,144 - routes.pdf_converter - INFO - File Conversion FINISH
2025-03-06 11:48:51,766 - routes.pdf_converter - INFO - JSON data published to DB successfully.
2025-03-06 11:48:51,766 - fastapi - INFO - Response: 200 | Time taken: 2.9620 sec
2025-03-06 17:35:55,163 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/
2025-03-06 17:35:55,165 - fastapi - INFO - Response: 200 | Time taken: 0.0022 sec
2025-03-06 17:36:10,347 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/
2025-03-06 17:36:10,348 - fastapi - INFO - Response: 200 | Time taken: 0.0006 sec
2025-03-06 17:36:13,751 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/upload
2025-03-06 17:36:13,752 - fastapi - INFO - Response: 200 | Time taken: 0.0011 sec
2025-03-06 17:36:25,097 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-06 17:36:25,149 - root - INFO - Received file '13.pdf' with provided password.
2025-03-06 17:36:25,149 - routes.pdf_converter - INFO - File Conversion START
2025-03-06 17:36:27,392 - routes.pdf_converter - INFO - File Conversion FINISH
2025-03-06 17:36:27,441 - routes.pdf_converter - INFO - Data published successfully.
2025-03-06 17:36:27,441 - fastapi - INFO - Response: 200 | Time taken: 2.3437 sec
2025-03-06 17:43:28,200 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-06 17:43:28,202 - root - INFO - Received file '13.pdf' with provided password.
2025-03-06 17:43:28,202 - routes.pdf_converter - INFO - File Conversion START
2025-03-06 17:43:30,507 - routes.pdf_converter - INFO - File Conversion FINISH
2025-03-06 17:43:30,554 - routes.pdf_converter - INFO - Data published successfully.
2025-03-06 17:43:30,555 - fastapi - INFO - Response: 200 | Time taken: 2.3549 sec
2025-03-06 17:45:44,537 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-06 17:45:44,625 - root - INFO - Received file '13.pdf' with provided password.
2025-03-06 17:45:44,625 - routes.pdf_converter - INFO - File Conversion START
2025-03-06 17:45:46,888 - routes.pdf_converter - INFO - File Conversion FINISH
2025-03-06 17:45:46,936 - routes.pdf_converter - INFO - Data published successfully.
2025-03-06 17:45:46,936 - fastapi - INFO - Response: 200 | Time taken: 2.3993 sec
2025-03-06 19:55:49,891 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-06 19:55:49,951 - root - INFO - Received file '13.pdf' with provided password.
2025-03-06 19:55:49,951 - routes.pdf_converter - INFO - File Conversion START
2025-03-06 19:55:52,894 - routes.pdf_converter - INFO - File Conversion FINISH
2025-03-06 19:55:53,098 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:55:53,102 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:55:53,103 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:55:53,105 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:55:53,106 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:55:53,108 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:55:53,109 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:55:53,112 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:55:53,114 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:55:53,117 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:55:53,118 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:55:53,119 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:55:53,120 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:55:53,124 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:55:53,125 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:55:53,126 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:55:53,127 - routes.pdf_converter - INFO - Data published successfully.
2025-03-06 19:55:53,128 - fastapi - INFO - Response: 200 | Time taken: 3.2362 sec
2025-03-06 19:59:02,078 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-06 19:59:02,133 - root - INFO - Received file '13.pdf' with provided password.
2025-03-06 19:59:02,133 - routes.pdf_converter - INFO - File Conversion START
2025-03-06 19:59:04,397 - routes.pdf_converter - INFO - File Conversion FINISH
2025-03-06 19:59:04,418 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:04,422 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:04,424 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:04,425 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:04,426 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:04,428 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:04,429 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:04,432 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:04,434 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:04,436 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:04,438 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:04,439 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:04,440 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:04,444 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:04,445 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:04,446 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:04,447 - routes.pdf_converter - INFO - Data published successfully.
2025-03-06 19:59:43,386 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-06 19:59:43,431 - root - INFO - Received file '13.pdf' with provided password.
2025-03-06 19:59:43,431 - routes.pdf_converter - INFO - File Conversion START
2025-03-06 19:59:45,708 - routes.pdf_converter - INFO - File Conversion FINISH
2025-03-06 19:59:45,762 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:45,767 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:45,768 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:45,769 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:45,770 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:45,772 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:45,773 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:45,776 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:45,778 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:45,781 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:45,782 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:45,783 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:45,784 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:45,788 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:45,789 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:45,790 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 19:59:45,791 - routes.pdf_converter - INFO - Data published successfully.
2025-03-06 20:00:38,182 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-06 20:00:38,236 - root - INFO - Received file '13.pdf' with provided password.
2025-03-06 20:00:38,236 - routes.pdf_converter - INFO - File Conversion START
2025-03-06 20:00:40,500 - routes.pdf_converter - INFO - File Conversion FINISH
2025-03-06 20:00:40,520 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:00:40,524 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:00:40,525 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:00:40,527 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:00:40,528 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:00:40,530 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:00:40,531 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:00:40,534 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:00:40,536 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:00:40,538 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:00:40,540 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:00:40,541 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:00:40,542 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:00:40,546 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:00:40,547 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:00:40,548 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:00:40,549 - routes.pdf_converter - INFO - Data published successfully.
2025-03-06 20:00:40,550 - fastapi - INFO - Response: 200 | Time taken: 2.3675 sec
2025-03-06 20:09:50,084 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-06 20:09:50,107 - root - INFO - Received file '13.pdf' with provided password.
2025-03-06 20:09:50,107 - routes.pdf_converter - INFO - File Conversion START
2025-03-06 20:09:52,371 - routes.pdf_converter - INFO - File Conversion FINISH
2025-03-06 20:09:52,394 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:09:52,398 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:09:52,399 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:09:52,401 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:09:52,402 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:09:52,404 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:09:52,405 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:09:52,408 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:09:52,410 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:09:52,412 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:09:52,414 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:09:52,415 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:09:52,416 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:09:52,419 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:09:52,420 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:09:52,421 - routes.pdf_converter - INFO - Existing Folio found
2025-03-06 20:09:52,422 - routes.pdf_converter - INFO - Data published successfully.
2025-03-06 20:09:52,423 - fastapi - INFO - Response: 200 | Time taken: 2.3392 sec
2025-03-06 20:13:16,916 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-06 20:13:16,939 - root - INFO - Received file '13.pdf' with provided password.
2025-03-06 20:13:16,939 - routes.pdf_converter - INFO - File Conversion START
2025-03-06 20:13:19,229 - routes.pdf_converter - INFO - File Conversion FINISH
2025-03-06 20:13:19,250 - routes.pdf_converter - INFO - Existing Folio found 1038436370 / 0
2025-03-06 20:13:19,254 - routes.pdf_converter - INFO - Existing Folio found 91057795155 / 0
2025-03-06 20:13:19,255 - routes.pdf_converter - INFO - Existing Folio found 1579147971 / 0
2025-03-06 20:13:19,257 - routes.pdf_converter - INFO - Existing Folio found 8087557 / 36
2025-03-06 20:13:19,258 - routes.pdf_converter - INFO - Existing Folio found 20444730 / 74
2025-03-06 20:13:19,259 - routes.pdf_converter - INFO - Existing Folio found 20857769 / 35
2025-03-06 20:13:19,260 - routes.pdf_converter - INFO - Existing Folio found 17950652 / 19
2025-03-06 20:13:19,263 - routes.pdf_converter - INFO - Existing Folio found 3106188532 / 0
2025-03-06 20:13:19,265 - routes.pdf_converter - INFO - Existing Folio found 12044129 / 16
2025-03-06 20:13:19,268 - routes.pdf_converter - INFO - Existing Folio found 91070834823 / 0
2025-03-06 20:13:19,269 - routes.pdf_converter - INFO - Existing Folio found 499280328614 / 0
2025-03-06 20:13:19,270 - routes.pdf_converter - INFO - Existing Folio found 14879696
2025-03-06 20:13:19,271 - routes.pdf_converter - INFO - Existing Folio found 51018328915 / 0
2025-03-06 20:13:19,275 - routes.pdf_converter - INFO - Existing Folio found 21211247 / 0
2025-03-06 20:13:19,276 - routes.pdf_converter - INFO - Existing Folio found 43142144 / 0
2025-03-06 20:13:19,277 - routes.pdf_converter - INFO - Existing Folio found 4351542 / 22
2025-03-06 20:13:19,278 - routes.pdf_converter - INFO - Data published successfully.
2025-03-06 20:13:19,278 - fastapi - INFO - Response: 200 | Time taken: 2.3624 sec
2025-03-06 20:14:09,965 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-06 20:14:10,036 - root - INFO - Received file '13.pdf' with provided password.
2025-03-06 20:14:10,036 - routes.pdf_converter - INFO - File Conversion START
2025-03-06 20:14:12,299 - routes.pdf_converter - INFO - File Conversion FINISH
2025-03-06 20:14:12,320 - routes.pdf_converter - INFO - Existing Folio found 1038436370 / 0 with Aditya Birla Sun Life Mutual Fund
2025-03-06 20:14:12,325 - routes.pdf_converter - INFO - Existing Folio found 91057795155 / 0 with AXIS Mutual Fund
2025-03-06 20:14:12,326 - routes.pdf_converter - INFO - Existing Folio found 1579147971 / 0 with Canara Robeco Mutual Fund
2025-03-06 20:14:12,327 - routes.pdf_converter - INFO - Existing Folio found 8087557 / 36 with DSP Mutual Fund
2025-03-06 20:14:12,328 - routes.pdf_converter - INFO - Existing Folio found 20444730 / 74 with HDFC Mutual Fund
2025-03-06 20:14:12,330 - routes.pdf_converter - INFO - Existing Folio found 20857769 / 35 with HSBC Mutual Fund
2025-03-06 20:14:12,331 - routes.pdf_converter - INFO - Existing Folio found 17950652 / 19 with ICICI Prudential Mutual Fund
2025-03-06 20:14:12,334 - routes.pdf_converter - INFO - Existing Folio found 3106188532 / 0 with Invesco Mutual Fund
2025-03-06 20:14:12,336 - routes.pdf_converter - INFO - Existing Folio found 12044129 / 16 with Kotak Mutual Fund
2025-03-06 20:14:12,338 - routes.pdf_converter - INFO - Existing Folio found 91070834823 / 0 with MOTILAL OSWAL MUTUAL FUND
2025-03-06 20:14:12,340 - routes.pdf_converter - INFO - Existing Folio found 499280328614 / 0 with Nippon India Mutual Fund
2025-03-06 20:14:12,341 - routes.pdf_converter - INFO - Existing Folio found 14879696 with PPFAS Mutual Fund
2025-03-06 20:14:12,342 - routes.pdf_converter - INFO - Existing Folio found 51018328915 / 0 with Quant MF
2025-03-06 20:14:12,346 - routes.pdf_converter - INFO - Existing Folio found 21211247 / 0 with SBI Mutual Fund
2025-03-06 20:14:12,347 - routes.pdf_converter - INFO - Existing Folio found 43142144 / 0 with SBI Mutual Fund
2025-03-06 20:14:12,348 - routes.pdf_converter - INFO - Existing Folio found 4351542 / 22 with Tata Mutual Fund
2025-03-06 20:14:12,349 - routes.pdf_converter - INFO - Data published successfully.
2025-03-06 20:14:12,349 - fastapi - INFO - Response: 200 | Time taken: 2.3848 sec
2025-03-06 21:53:58,955 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-06 21:53:59,007 - root - INFO - Received file '13.pdf' with provided password.
2025-03-06 21:53:59,007 - routes.pdf_converter - INFO - File Conversion START
2025-03-06 21:54:01,311 - routes.pdf_converter - INFO - File Conversion FINISH
2025-03-06 21:54:01,314 - routes.pdf_converter - INFO - Existing Folio found 1038436370 / 0 with Aditya Birla Sun Life Mutual Fund
2025-03-06 21:54:01,315 - routes.pdf_converter - INFO - Existing Folio found 91057795155 / 0 with AXIS Mutual Fund
2025-03-06 21:54:01,317 - routes.pdf_converter - INFO - Existing Folio found 1579147971 / 0 with Canara Robeco Mutual Fund
2025-03-06 21:54:01,318 - routes.pdf_converter - INFO - Existing Folio found 8087557 / 36 with DSP Mutual Fund
2025-03-06 21:54:01,319 - routes.pdf_converter - INFO - Existing Folio found 20444730 / 74 with HDFC Mutual Fund
2025-03-06 21:54:01,321 - routes.pdf_converter - INFO - Existing Folio found 20857769 / 35 with HSBC Mutual Fund
2025-03-06 21:54:01,322 - routes.pdf_converter - INFO - Existing Folio found 17950652 / 19 with ICICI Prudential Mutual Fund
2025-03-06 21:54:01,325 - routes.pdf_converter - INFO - Existing Folio found 3106188532 / 0 with Invesco Mutual Fund
2025-03-06 21:54:01,327 - routes.pdf_converter - INFO - Existing Folio found 12044129 / 16 with Kotak Mutual Fund
2025-03-06 21:54:01,329 - routes.pdf_converter - INFO - Existing Folio found 91070834823 / 0 with MOTILAL OSWAL MUTUAL FUND
2025-03-06 21:54:01,331 - routes.pdf_converter - INFO - Existing Folio found 499280328614 / 0 with Nippon India Mutual Fund
2025-03-06 21:54:01,332 - routes.pdf_converter - INFO - Existing Folio found 14879696 with PPFAS Mutual Fund
2025-03-06 21:54:01,333 - routes.pdf_converter - INFO - Existing Folio found 51018328915 / 0 with Quant MF
2025-03-06 21:54:01,337 - routes.pdf_converter - INFO - Existing Folio found 21211247 / 0 with SBI Mutual Fund
2025-03-06 21:54:01,338 - routes.pdf_converter - INFO - Existing Folio found 43142144 / 0 with SBI Mutual Fund
2025-03-06 21:54:01,339 - routes.pdf_converter - INFO - Existing Folio found 4351542 / 22 with Tata Mutual Fund
2025-03-06 21:54:01,340 - routes.pdf_converter - INFO - Data published successfully.
2025-03-06 21:54:01,340 - fastapi - INFO - Response: 200 | Time taken: 2.3859 sec
2025-03-06 21:54:29,450 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-06 21:54:29,473 - root - INFO - Received file '13.pdf' with provided password.
2025-03-06 21:54:29,473 - routes.pdf_converter - INFO - File Conversion START
2025-03-06 21:54:31,832 - routes.pdf_converter - INFO - File Conversion FINISH
2025-03-06 21:54:31,852 - routes.pdf_converter - INFO - Existing Folio found 1038436370 / 0 with Aditya Birla Sun Life Mutual Fund
2025-03-06 21:54:32,104 - routes.pdf_converter - ERROR - Error publishing JSON to DB, Exception: (psycopg2.errors.UndefinedColumn) column statement_period.user_id does not exist
LINE 1: ...ement_period.to_date AS statement_period_to_date, statement_...
                                                             ^

[SQL: SELECT statement_period.id AS statement_period_id, statement_period.from_date AS statement_period_from_date, statement_period.to_date AS statement_period_to_date, statement_period.user_id AS statement_period_user_id 
FROM statement_period 
WHERE statement_period.id = %(pk_1)s]
[parameters: {'pk_1': 1}]
(Background on this error at: https://sqlalche.me/e/20/f405)
Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column statement_period.user_id does not exist
LINE 1: ...ement_period.to_date AS statement_period_to_date, statement_...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/routes/pdf_converter.py", line 255, in publish_json_to_db
    sp = existing_folio.statement_period
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 563, in __get__
    return self.impl.get(state, dict_)  # type: ignore[no-any-return]
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1083, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1118, in _fire_loader_callables
    return self.callable_(state, passive)
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 966, in _load_for_state
    return self._emit_lazyload(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 1067, in _emit_lazyload
    return loading.load_on_pk_identity(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 666, in load_on_pk_identity
    session.execute(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2246, in execute
    return self._execute_internal(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2141, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column statement_period.user_id does not exist
LINE 1: ...ement_period.to_date AS statement_period_to_date, statement_...
                                                             ^

[SQL: SELECT statement_period.id AS statement_period_id, statement_period.from_date AS statement_period_from_date, statement_period.to_date AS statement_period_to_date, statement_period.user_id AS statement_period_user_id 
FROM statement_period 
WHERE statement_period.id = %(pk_1)s]
[parameters: {'pk_1': 1}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-03-06 21:54:32,300 - routes.pdf_converter - ERROR - Failed to push data to DB.
2025-03-06 22:41:47,441 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/
2025-03-06 22:41:47,493 - fastapi - INFO - Response: 200 | Time taken: 0.0529 sec
2025-03-06 22:41:51,525 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/upload
2025-03-06 22:41:51,571 - fastapi - INFO - Response: 200 | Time taken: 0.0459 sec
2025-03-06 22:42:02,376 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-06 22:42:02,433 - root - INFO - Received file '13.pdf' with provided password.
2025-03-06 22:42:02,433 - routes.pdf_converter - INFO - File Conversion START
2025-03-06 22:42:04,711 - routes.pdf_converter - INFO - File Conversion FINISH
2025-03-06 22:42:04,732 - routes.pdf_converter - INFO - Existing Folio found 1038436370 / 0 with Aditya Birla Sun Life Mutual Fund
2025-03-06 22:42:04,737 - routes.pdf_converter - INFO - Existing Folio found 91057795155 / 0 with AXIS Mutual Fund
2025-03-06 22:42:04,738 - routes.pdf_converter - INFO - Existing Folio found 1579147971 / 0 with Canara Robeco Mutual Fund
2025-03-06 22:42:04,739 - routes.pdf_converter - INFO - Existing Folio found 8087557 / 36 with DSP Mutual Fund
2025-03-06 22:42:04,740 - routes.pdf_converter - INFO - Existing Folio found 20444730 / 74 with HDFC Mutual Fund
2025-03-06 22:42:04,742 - routes.pdf_converter - INFO - Existing Folio found 20857769 / 35 with HSBC Mutual Fund
2025-03-06 22:42:04,743 - routes.pdf_converter - INFO - Existing Folio found 17950652 / 19 with ICICI Prudential Mutual Fund
2025-03-06 22:42:04,746 - routes.pdf_converter - INFO - Existing Folio found 3106188532 / 0 with Invesco Mutual Fund
2025-03-06 22:42:04,748 - routes.pdf_converter - INFO - Existing Folio found 12044129 / 16 with Kotak Mutual Fund
2025-03-06 22:42:04,751 - routes.pdf_converter - INFO - Existing Folio found 91070834823 / 0 with MOTILAL OSWAL MUTUAL FUND
2025-03-06 22:42:04,752 - routes.pdf_converter - INFO - Existing Folio found 499280328614 / 0 with Nippon India Mutual Fund
2025-03-06 22:42:04,753 - routes.pdf_converter - INFO - Existing Folio found 14879696 with PPFAS Mutual Fund
2025-03-06 22:42:04,754 - routes.pdf_converter - INFO - Existing Folio found 51018328915 / 0 with Quant MF
2025-03-06 22:42:04,758 - routes.pdf_converter - INFO - Existing Folio found 21211247 / 0 with SBI Mutual Fund
2025-03-06 22:42:04,759 - routes.pdf_converter - INFO - Existing Folio found 43142144 / 0 with SBI Mutual Fund
2025-03-06 22:42:04,760 - routes.pdf_converter - INFO - Existing Folio found 4351542 / 22 with Tata Mutual Fund
2025-03-06 22:42:04,761 - routes.pdf_converter - INFO - Data published successfully.
2025-03-06 22:42:04,762 - fastapi - INFO - Response: 200 | Time taken: 2.3859 sec
2025-03-06 22:43:40,199 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-06 22:43:40,272 - root - INFO - Received file '13.pdf' with provided password.
2025-03-06 22:43:40,272 - routes.pdf_converter - INFO - Cleaning up DB for Test
2025-03-06 22:43:40,272 - routes.pdf_converter - INFO - Starting to clean database.
2025-03-06 22:43:40,272 - routes.pdf_converter - ERROR - Error in cleaning the db for test 'sessionmaker' object has no attribute 'rollback'
2025-03-06 22:43:40,272 - root - INFO - Error in execution 'NoneType' object is not iterable
2025-03-06 22:43:40,273 - fastapi - INFO - Response: 200 | Time taken: 0.0739 sec
2025-03-06 22:58:42,129 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-06 22:58:42,159 - root - INFO - Received file '13.pdf' with provided password.
2025-03-06 22:58:42,159 - Converter - INFO - Cleaning up DB for Test
2025-03-06 22:58:42,159 - Converter - INFO - Starting to clean database.
2025-03-06 22:58:42,159 - Converter - ERROR - Error in cleaning the db for test 'sessionmaker' object has no attribute 'rollback'
2025-03-06 22:58:42,159 - root - INFO - Error in execution 'NoneType' object is not iterable
2025-03-06 22:58:42,159 - fastapi - INFO - Response: 200 | Time taken: 0.0307 sec
2025-03-06 22:59:39,152 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/upload
2025-03-06 22:59:39,154 - fastapi - INFO - Response: 200 | Time taken: 0.0023 sec
2025-03-06 22:59:52,840 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-06 22:59:52,902 - root - INFO - Received file '13.pdf' with provided password.
2025-03-06 22:59:52,902 - Converter - INFO - Cleaning up DB for Test
2025-03-06 22:59:52,902 - Converter - INFO - Starting to clean database.
2025-03-06 22:59:52,902 - Converter - ERROR - Error in cleaning the db for test 'sessionmaker' object has no attribute 'rollback'
2025-03-06 22:59:52,902 - root - INFO - Error in execution 'NoneType' object is not iterable
2025-03-06 22:59:52,902 - fastapi - INFO - Response: 200 | Time taken: 0.0625 sec
2025-03-06 23:00:30,860 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-06 23:00:30,881 - root - INFO - Received file '13.pdf' with provided password.
2025-03-06 23:00:30,881 - Converter - INFO - Cleaning up DB for Test
2025-03-06 23:01:13,097 - Converter - INFO - Starting to clean database.
2025-03-06 23:09:14,976 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/upload
2025-03-06 23:09:14,984 - fastapi - INFO - Response: 200 | Time taken: 0.0074 sec
2025-03-06 23:09:23,674 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-06 23:09:23,730 - root - INFO - Received file '13.pdf' with provided password.
2025-03-06 23:09:38,302 - Converter - INFO - Starting to clean database.
2025-03-06 23:10:00,173 - Converter - INFO - Found user_id ac1ae588-280c-4c80-b05d-ce66528a047b for email test@ting.com
2025-03-06 23:10:00,174 - Converter - INFO - Retrieving folios for deletion.
2025-03-06 23:10:00,242 - Converter - INFO - Transactions deleted for user ac1ae588-280c-4c80-b05d-ce66528a047b
2025-03-06 23:10:00,244 - Converter - INFO - Valuations deleted for user ac1ae588-280c-4c80-b05d-ce66528a047b
2025-03-06 23:10:00,247 - Converter - INFO - Schemes deleted for user ac1ae588-280c-4c80-b05d-ce66528a047b
2025-03-06 23:10:00,249 - Converter - INFO - Folios deleted for user ac1ae588-280c-4c80-b05d-ce66528a047b
2025-03-06 23:10:00,252 - Converter - INFO - StatementPeriod 1 deleted for user ac1ae588-280c-4c80-b05d-ce66528a047b
2025-03-06 23:10:00,252 - Converter - INFO - StatementPeriods cleanup completed for user ac1ae588-280c-4c80-b05d-ce66528a047b
2025-03-06 23:10:00,253 - Converter - INFO - User ac1ae588-280c-4c80-b05d-ce66528a047b deleted
2025-03-06 23:10:00,354 - Converter - INFO - Database cleared for email: test@ting.com
2025-03-06 23:10:00,355 - root - INFO - Error in execution 'NoneType' object is not iterable
2025-03-06 23:10:00,356 - fastapi - INFO - Response: 200 | Time taken: 36.6820 sec
2025-03-06 23:12:31,021 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-06 23:12:31,040 - root - INFO - Received file '13.pdf' with provided password.
2025-03-06 23:12:31,040 - Converter - INFO - File Conversion START
2025-03-06 23:12:35,869 - Converter - INFO - File Conversion FINISH
2025-03-06 23:12:35,903 - Converter - ERROR - User with email test@ting.com not found.
2025-03-06 23:12:35,904 - Converter - ERROR - Error publishing JSON to DB, Exception: User not found.
Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/routes/pdf_converter.py", line 169, in publish_json_to_db
    raise ValueError("User not found.")
ValueError: User not found.
2025-03-06 23:12:35,904 - Converter - ERROR - Failed to push data to DB.
2025-03-06 23:12:35,904 - root - INFO - Error in execution 'NoneType' object is not iterable
2025-03-06 23:12:35,905 - fastapi - INFO - Response: 200 | Time taken: 4.8835 sec
2025-03-06 23:13:47,346 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-06 23:13:47,368 - root - INFO - Received file '13.pdf' with provided password.
2025-03-06 23:13:47,368 - Converter - INFO - File Conversion START
2025-03-06 23:13:52,210 - Converter - INFO - File Conversion FINISH
2025-03-06 23:13:52,212 - Converter - ERROR - User with email test@ting.com not found.
2025-03-06 23:13:52,212 - Converter - ERROR - Error publishing JSON to DB, Exception: User not found.
Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/routes/pdf_converter.py", line 169, in publish_json_to_db
    raise ValueError("User not found.")
ValueError: User not found.
2025-03-06 23:13:52,213 - Converter - ERROR - Failed to push data to DB.
2025-03-06 23:13:52,213 - root - INFO - Error in execution 'NoneType' object is not iterable
2025-03-06 23:13:52,213 - fastapi - INFO - Response: 200 | Time taken: 4.8676 sec
2025-03-06 23:14:38,842 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-06 23:14:38,869 - root - INFO - Received file '13.pdf' with provided password.
2025-03-06 23:14:47,014 - Converter - INFO - File Conversion START
2025-03-06 23:15:05,583 - Converter - INFO - File Conversion FINISH
2025-03-06 23:18:10,326 - Converter - ERROR - User with email test@ting.com not found.
2025-03-06 23:18:39,610 - Converter - ERROR - Error publishing JSON to DB, Exception: User not found.
Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/routes/pdf_converter.py", line 169, in publish_json_to_db
    raise ValueError("User not found.")
ValueError: User not found.
2025-03-06 23:20:59,167 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/upload
2025-03-06 23:20:59,169 - fastapi - INFO - Response: 200 | Time taken: 0.0022 sec
2025-03-06 23:21:02,352 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/
2025-03-06 23:21:02,353 - fastapi - INFO - Response: 200 | Time taken: 0.0013 sec
2025-03-06 23:21:09,555 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/register
2025-03-06 23:21:09,702 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-03-06 23:21:10,079 - fastapi - INFO - Response: 200 | Time taken: 0.5241 sec
2025-03-06 23:21:16,870 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/auth/login
2025-03-06 23:21:17,232 - fastapi - INFO - Response: 200 | Time taken: 0.3622 sec
2025-03-06 23:21:19,659 - fastapi - INFO - User: Anonymous | Request: GET http://localhost:8000/upload
2025-03-06 23:21:19,659 - fastapi - INFO - Response: 200 | Time taken: 0.0006 sec
2025-03-06 23:21:34,032 - fastapi - WARNING - Rate limit exceeded for IP: 127.0.0.1
2025-03-06 23:23:03,618 - fastapi - INFO - User: Anonymous | Request: POST http://localhost:8000/uploading
2025-03-06 23:23:03,637 - root - INFO - Received file '13.pdf' with provided password.
2025-03-06 23:23:03,637 - Converter - INFO - File Conversion START
2025-03-06 23:23:05,939 - Converter - INFO - File Conversion FINISH
2025-03-06 23:23:05,956 - Converter - ERROR - Error publishing JSON to DB, Exception: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "uq_statement_period_user"
DETAIL:  Key (user_id, from_date, to_date)=(044b16fa-099e-49d8-a828-828889e7c46f, 1985-01-01, 2025-02-15) already exists.

[SQL: INSERT INTO statement_period (from_date, to_date, user_id) VALUES (%(from_date)s, %(to_date)s, %(user_id)s) RETURNING statement_period.id]
[parameters: {'from_date': datetime.date(1985, 1, 1), 'to_date': datetime.date(2025, 2, 15), 'user_id': '044b16fa-099e-49d8-a828-828889e7c46f'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "uq_statement_period_user"
DETAIL:  Key (user_id, from_date, to_date)=(044b16fa-099e-49d8-a828-828889e7c46f, 1985-01-01, 2025-02-15) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/routes/pdf_converter.py", line 193, in publish_json_to_db
    session.flush()  # assign an id to sp
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4163, in flush
    self._flush(objects)
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4298, in _flush
    with util.safe_reraise():
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4259, in _flush
    flush_context.execute()
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1226, in _emit_insert_statements
    result = connection.execute(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "uq_statement_period_user"
DETAIL:  Key (user_id, from_date, to_date)=(044b16fa-099e-49d8-a828-828889e7c46f, 1985-01-01, 2025-02-15) already exists.

[SQL: INSERT INTO statement_period (from_date, to_date, user_id) VALUES (%(from_date)s, %(to_date)s, %(user_id)s) RETURNING statement_period.id]
[parameters: {'from_date': datetime.date(1985, 1, 1), 'to_date': datetime.date(2025, 2, 15), 'user_id': '044b16fa-099e-49d8-a828-828889e7c46f'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-03-06 23:23:06,025 - Converter - ERROR - Failed to push data to DB.
2025-03-06 23:23:06,025 - root - INFO - Error in execution 'NoneType' object is not iterable
2025-03-06 23:23:06,025 - fastapi - INFO - Response: 200 | Time taken: 2.4075 sec
2025-03-07 11:52:05,909 - fastapi - INFO - User: Anonymous | Request: GET http://172.16.16.40:8000/
2025-03-07 11:52:05,912 - fastapi - INFO - Response: 200 | Time taken: 0.0024 sec
2025-03-07 11:52:06,012 - fastapi - INFO - User: Anonymous | Request: GET http://172.16.16.40:8000/favicon.ico
2025-03-07 11:52:06,012 - fastapi - INFO - Response: 404 | Time taken: 0.0003 sec
2025-03-07 11:52:15,211 - fastapi - INFO - User: Anonymous | Request: POST http://172.16.16.40:8000/auth/login
2025-03-07 11:52:15,279 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-03-07 11:52:15,458 - fastapi - INFO - Response: 200 | Time taken: 0.2470 sec
2025-03-07 11:52:21,227 - fastapi - INFO - User: Anonymous | Request: GET http://172.16.16.40:8000/upload
2025-03-07 11:52:21,228 - fastapi - INFO - Response: 200 | Time taken: 0.0011 sec
2025-03-07 11:52:37,494 - fastapi - INFO - User: Anonymous | Request: POST http://172.16.16.40:8000/uploading
2025-03-07 11:52:37,563 - root - INFO - Received file '13.pdf' with provided password.
2025-03-07 11:52:37,563 - Converter - INFO - File Conversion START
2025-03-07 11:52:39,838 - Converter - INFO - File Conversion FINISH
2025-03-07 11:52:39,877 - Converter - ERROR - Error publishing JSON to DB, Exception: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "uq_statement_period_user"
DETAIL:  Key (user_id, from_date, to_date)=(044b16fa-099e-49d8-a828-828889e7c46f, 1985-01-01, 2025-02-15) already exists.

[SQL: INSERT INTO statement_period (from_date, to_date, user_id) VALUES (%(from_date)s, %(to_date)s, %(user_id)s) RETURNING statement_period.id]
[parameters: {'from_date': datetime.date(1985, 1, 1), 'to_date': datetime.date(2025, 2, 15), 'user_id': '044b16fa-099e-49d8-a828-828889e7c46f'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "uq_statement_period_user"
DETAIL:  Key (user_id, from_date, to_date)=(044b16fa-099e-49d8-a828-828889e7c46f, 1985-01-01, 2025-02-15) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/routes/pdf_converter.py", line 193, in publish_json_to_db
    session.flush()  # assign an id to sp
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4163, in flush
    self._flush(objects)
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4298, in _flush
    with util.safe_reraise():
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4259, in _flush
    flush_context.execute()
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1226, in _emit_insert_statements
    result = connection.execute(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "uq_statement_period_user"
DETAIL:  Key (user_id, from_date, to_date)=(044b16fa-099e-49d8-a828-828889e7c46f, 1985-01-01, 2025-02-15) already exists.

[SQL: INSERT INTO statement_period (from_date, to_date, user_id) VALUES (%(from_date)s, %(to_date)s, %(user_id)s) RETURNING statement_period.id]
[parameters: {'from_date': datetime.date(1985, 1, 1), 'to_date': datetime.date(2025, 2, 15), 'user_id': '044b16fa-099e-49d8-a828-828889e7c46f'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-03-07 11:52:39,879 - Converter - ERROR - Failed to push data to DB.
2025-03-07 11:52:39,879 - root - INFO - Error in execution 'NoneType' object is not iterable
2025-03-07 11:52:39,879 - fastapi - INFO - Response: 200 | Time taken: 2.3849 sec
2025-03-07 11:55:21,931 - fastapi - INFO - User: Anonymous | Request: POST http://172.16.16.40:8000/uploading
2025-03-07 11:55:21,947 - root - INFO - Received file '13.pdf' with provided password.
2025-03-07 11:55:45,040 - Converter - INFO - File Conversion START
2025-03-07 11:56:36,476 - Converter - INFO - File Conversion FINISH
2025-03-07 12:02:56,641 - fastapi - INFO - User: Anonymous | Request: POST http://172.16.16.40:8000/uploading
2025-03-07 12:02:56,684 - root - INFO - Received file '13.pdf' with provided password.
2025-03-07 12:02:56,684 - Converter - INFO - File Conversion START
2025-03-07 12:02:58,950 - Converter - INFO - File Conversion FINISH
2025-03-07 12:02:58,982 - Converter - ERROR - Error publishing JSON to DB, Exception: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "uq_statement_period_user"
DETAIL:  Key (user_id, from_date, to_date)=(044b16fa-099e-49d8-a828-828889e7c46f, 1985-01-01, 2025-02-15) already exists.

[SQL: INSERT INTO statement_period (from_date, to_date, user_id) VALUES (%(from_date)s, %(to_date)s, %(user_id)s) RETURNING statement_period.id]
[parameters: {'from_date': datetime.date(1985, 1, 1), 'to_date': datetime.date(2025, 2, 15), 'user_id': '044b16fa-099e-49d8-a828-828889e7c46f'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "uq_statement_period_user"
DETAIL:  Key (user_id, from_date, to_date)=(044b16fa-099e-49d8-a828-828889e7c46f, 1985-01-01, 2025-02-15) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/routes/pdf_converter.py", line 193, in publish_json_to_db
    session.flush()  # assign an id to sp
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4163, in flush
    self._flush(objects)
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4298, in _flush
    with util.safe_reraise():
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4259, in _flush
    flush_context.execute()
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1226, in _emit_insert_statements
    result = connection.execute(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "uq_statement_period_user"
DETAIL:  Key (user_id, from_date, to_date)=(044b16fa-099e-49d8-a828-828889e7c46f, 1985-01-01, 2025-02-15) already exists.

[SQL: INSERT INTO statement_period (from_date, to_date, user_id) VALUES (%(from_date)s, %(to_date)s, %(user_id)s) RETURNING statement_period.id]
[parameters: {'from_date': datetime.date(1985, 1, 1), 'to_date': datetime.date(2025, 2, 15), 'user_id': '044b16fa-099e-49d8-a828-828889e7c46f'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-03-07 12:02:58,984 - Converter - ERROR - Failed to push data to DB.
2025-03-07 12:02:58,984 - root - INFO - Error in execution 'NoneType' object is not iterable
2025-03-07 12:02:58,985 - fastapi - INFO - Response: 200 | Time taken: 2.3434 sec
2025-03-07 12:26:02,294 - fastapi - INFO - User: Anonymous | Request: POST http://172.16.16.40:8000/uploading
2025-03-07 12:26:02,358 - root - INFO - Received file '13.pdf' with provided password.
2025-03-07 12:26:02,358 - Converter - INFO - File Conversion START
2025-03-07 12:26:04,633 - Converter - INFO - File Conversion FINISH
2025-03-07 12:26:05,076 - Converter - INFO - Data published successfully.
2025-03-07 12:26:05,077 - fastapi - INFO - Response: 200 | Time taken: 2.7831 sec
2025-03-07 12:38:16,355 - fastapi - INFO - User: Anonymous | Request: POST http://172.16.16.40:8000/uploading
2025-03-07 12:38:16,376 - root - INFO - Received file '13.pdf' with provided password.
2025-03-07 12:38:16,376 - Converter - INFO - File Conversion START
2025-03-07 12:38:18,650 - Converter - INFO - File Conversion FINISH
2025-03-07 12:38:18,672 - Converter - INFO - Existing Folio found 1038436370 / 0 with Aditya Birla Sun Life Mutual Fund
2025-03-07 12:38:18,676 - Converter - INFO - Existing Folio found 91057795155 / 0 with AXIS Mutual Fund
2025-03-07 12:38:18,677 - Converter - INFO - Existing Folio found 1579147971 / 0 with Canara Robeco Mutual Fund
2025-03-07 12:38:18,679 - Converter - INFO - Existing Folio found 8087557 / 36 with DSP Mutual Fund
2025-03-07 12:38:18,680 - Converter - INFO - Existing Folio found 20444730 / 74 with HDFC Mutual Fund
2025-03-07 12:38:18,682 - Converter - INFO - Existing Folio found 20857769 / 35 with HSBC Mutual Fund
2025-03-07 12:38:18,683 - Converter - INFO - Existing Folio found 17950652 / 19 with ICICI Prudential Mutual Fund
2025-03-07 12:38:18,686 - Converter - INFO - Existing Folio found 3106188532 / 0 with Invesco Mutual Fund
2025-03-07 12:38:18,688 - Converter - INFO - Existing Folio found 12044129 / 16 with Kotak Mutual Fund
2025-03-07 12:38:18,691 - Converter - INFO - Existing Folio found 91070834823 / 0 with MOTILAL OSWAL MUTUAL FUND
2025-03-07 12:38:18,692 - Converter - INFO - Existing Folio found 499280328614 / 0 with Nippon India Mutual Fund
2025-03-07 12:38:18,693 - Converter - INFO - Existing Folio found 14879696 with PPFAS Mutual Fund
2025-03-07 12:38:18,695 - Converter - INFO - Existing Folio found 51018328915 / 0 with Quant MF
2025-03-07 12:38:18,699 - Converter - INFO - Existing Folio found 21211247 / 0 with SBI Mutual Fund
2025-03-07 12:38:18,700 - Converter - INFO - Existing Folio found 43142144 / 0 with SBI Mutual Fund
2025-03-07 12:38:18,701 - Converter - INFO - Existing Folio found 4351542 / 22 with Tata Mutual Fund
2025-03-07 12:38:18,702 - Converter - INFO - Data published successfully.
2025-03-07 12:38:18,702 - fastapi - INFO - Response: 200 | Time taken: 2.3470 sec
2025-03-07 12:44:50,580 - fastapi - INFO - User: Anonymous | Request: POST http://172.16.16.40:8000/uploading
2025-03-07 12:44:50,629 - fastapi - INFO - Received file '13.pdf' with provided password.
2025-03-07 12:44:50,629 - Converter - INFO - File Conversion START
2025-03-07 12:44:52,894 - Converter - INFO - File Conversion FINISH
2025-03-07 12:44:52,915 - Converter - INFO - Existing Folio found 1038436370 / 0 with Aditya Birla Sun Life Mutual Fund
2025-03-07 12:44:52,919 - Converter - INFO - Existing Folio found 91057795155 / 0 with AXIS Mutual Fund
2025-03-07 12:44:52,920 - Converter - INFO - Existing Folio found 1579147971 / 0 with Canara Robeco Mutual Fund
2025-03-07 12:44:52,921 - Converter - INFO - Existing Folio found 8087557 / 36 with DSP Mutual Fund
2025-03-07 12:44:52,922 - Converter - INFO - Existing Folio found 20444730 / 74 with HDFC Mutual Fund
2025-03-07 12:44:52,924 - Converter - INFO - Existing Folio found 20857769 / 35 with HSBC Mutual Fund
2025-03-07 12:44:52,925 - Converter - INFO - Existing Folio found 17950652 / 19 with ICICI Prudential Mutual Fund
2025-03-07 12:44:52,928 - Converter - INFO - Existing Folio found 3106188532 / 0 with Invesco Mutual Fund
2025-03-07 12:44:52,931 - Converter - INFO - Existing Folio found 12044129 / 16 with Kotak Mutual Fund
2025-03-07 12:44:52,933 - Converter - INFO - Existing Folio found 91070834823 / 0 with MOTILAL OSWAL MUTUAL FUND
2025-03-07 12:44:52,934 - Converter - INFO - Existing Folio found 499280328614 / 0 with Nippon India Mutual Fund
2025-03-07 12:44:52,935 - Converter - INFO - Existing Folio found 14879696 with PPFAS Mutual Fund
2025-03-07 12:44:52,936 - Converter - INFO - Existing Folio found 51018328915 / 0 with Quant MF
2025-03-07 12:44:52,940 - Converter - INFO - Existing Folio found 21211247 / 0 with SBI Mutual Fund
2025-03-07 12:44:52,941 - Converter - INFO - Existing Folio found 43142144 / 0 with SBI Mutual Fund
2025-03-07 12:44:52,941 - Converter - INFO - Existing Folio found 4351542 / 22 with Tata Mutual Fund
2025-03-07 12:44:52,942 - Converter - INFO - Finished DB query.
2025-03-07 12:44:52,943 - fastapi - INFO - Response: 200 | Time taken: 2.3624 sec
2025-03-07 12:45:34,657 - fastapi - INFO - User: Anonymous | Request: POST http://172.16.16.40:8000/uploading
2025-03-07 12:45:34,691 - fastapi - INFO - Received file '13.pdf' with provided password.
2025-03-07 12:45:34,692 - Converter - INFO - Starting to clean database.
2025-03-07 12:45:34,711 - Converter - INFO - Found user_id 044b16fa-099e-49d8-a828-828889e7c46f for email test@ting.com
2025-03-07 12:45:34,711 - Converter - INFO - Retrieving folios for deletion.
2025-03-07 12:45:34,717 - Converter - INFO - Transactions deleted for user 044b16fa-099e-49d8-a828-828889e7c46f
2025-03-07 12:45:34,718 - Converter - INFO - Valuations deleted for user 044b16fa-099e-49d8-a828-828889e7c46f
2025-03-07 12:45:34,719 - Converter - INFO - Schemes deleted for user 044b16fa-099e-49d8-a828-828889e7c46f
2025-03-07 12:45:34,721 - Converter - INFO - Folios deleted for user 044b16fa-099e-49d8-a828-828889e7c46f
2025-03-07 12:45:34,722 - Converter - INFO - StatementPeriod 8 deleted for user 044b16fa-099e-49d8-a828-828889e7c46f
2025-03-07 12:45:34,722 - Converter - INFO - StatementPeriods cleanup completed for user 044b16fa-099e-49d8-a828-828889e7c46f
2025-03-07 12:45:34,723 - Converter - INFO - User 044b16fa-099e-49d8-a828-828889e7c46f deleted
2025-03-07 12:45:34,785 - Converter - INFO - Database cleared for email: test@ting.com
2025-03-07 12:45:34,786 - fastapi - INFO - Response: 200 | Time taken: 0.1291 sec
2025-03-07 12:49:41,596 - fastapi - INFO - User: Anonymous | Request: POST http://172.16.16.40:8000/uploading
2025-03-07 12:49:41,663 - fastapi - INFO - Received file '13.pdf' with provided password.
2025-03-07 12:49:41,663 - Converter - INFO - File Conversion START
2025-03-07 12:49:43,983 - Converter - INFO - File Conversion FINISH
2025-03-07 12:49:44,015 - Converter - INFO - Using existing statement period
2025-03-07 12:49:44,019 - Converter - INFO - Using existing statement period
2025-03-07 12:49:44,028 - Converter - INFO - Using existing statement period
2025-03-07 12:49:44,048 - Converter - INFO - Using existing statement period
2025-03-07 12:49:44,056 - Converter - INFO - Using existing statement period
2025-03-07 12:49:44,060 - Converter - INFO - Using existing statement period
2025-03-07 12:49:44,072 - Converter - INFO - Using existing statement period
2025-03-07 12:49:44,081 - Converter - INFO - Using existing statement period
2025-03-07 12:49:44,091 - Converter - INFO - Using existing statement period
2025-03-07 12:49:44,097 - Converter - INFO - Using existing statement period
2025-03-07 12:49:44,101 - Converter - INFO - Using existing statement period
2025-03-07 12:49:44,105 - Converter - INFO - Using existing statement period
2025-03-07 12:49:44,121 - Converter - INFO - Using existing statement period
2025-03-07 12:49:44,125 - Converter - INFO - Using existing statement period
2025-03-07 12:49:44,129 - Converter - INFO - Using existing statement period
2025-03-07 12:49:44,144 - Converter - INFO - Finished DB query.
2025-03-07 12:49:44,144 - fastapi - INFO - Response: 200 | Time taken: 2.5479 sec
2025-03-07 12:50:16,458 - fastapi - INFO - User: Anonymous | Request: GET http://172.16.16.40:8000/
2025-03-07 12:50:16,461 - fastapi - INFO - Response: 200 | Time taken: 0.0023 sec
2025-03-07 12:50:22,720 - fastapi - INFO - User: Anonymous | Request: POST http://172.16.16.40:8000/auth/register
2025-03-07 12:50:22,725 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-03-07 12:50:22,931 - fastapi - INFO - Response: 200 | Time taken: 0.2108 sec
2025-03-07 12:51:29,814 - fastapi - INFO - User: Anonymous | Request: GET http://172.16.16.40:8000/upload
2025-03-07 12:51:29,816 - fastapi - INFO - Response: 200 | Time taken: 0.0022 sec
2025-03-07 12:51:40,951 - fastapi - INFO - User: Anonymous | Request: POST http://172.16.16.40:8000/uploading
2025-03-07 12:51:41,022 - fastapi - INFO - Received file '13.pdf' with provided password.
2025-03-07 12:51:41,022 - Converter - INFO - File Conversion START
2025-03-07 12:51:43,285 - Converter - INFO - File Conversion FINISH
2025-03-07 12:51:43,311 - Converter - ERROR - Error publishing JSON to DB, Exception: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "uq_folio_statement_period"
DETAIL:  Key (folio_number)=(1038436370 / 0) already exists.

[SQL: INSERT INTO folio (statement_period_id, folio_number, user_id, amc, pan) VALUES (%(statement_period_id)s, %(folio_number)s, %(user_id)s, %(amc)s, %(pan)s)]
[parameters: {'statement_period_id': 10, 'folio_number': '1038436370 / 0', 'user_id': 'ddba61f3-cde5-48bf-a3b2-4c364bd89855', 'amc': 'Aditya Birla Sun Life Mutual Fund', 'pan': 'AVYPR0077R'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "uq_folio_statement_period"
DETAIL:  Key (folio_number)=(1038436370 / 0) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/routes/pdf_converter.py", line 222, in publish_json_to_db
    session.flush()
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4163, in flush
    self._flush(objects)
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4298, in _flush
    with util.safe_reraise():
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4259, in _flush
    flush_context.execute()
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1043, in _emit_insert_statements
    result = connection.execute(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "uq_folio_statement_period"
DETAIL:  Key (folio_number)=(1038436370 / 0) already exists.

[SQL: INSERT INTO folio (statement_period_id, folio_number, user_id, amc, pan) VALUES (%(statement_period_id)s, %(folio_number)s, %(user_id)s, %(amc)s, %(pan)s)]
[parameters: {'statement_period_id': 10, 'folio_number': '1038436370 / 0', 'user_id': 'ddba61f3-cde5-48bf-a3b2-4c364bd89855', 'amc': 'Aditya Birla Sun Life Mutual Fund', 'pan': 'AVYPR0077R'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-03-07 12:51:43,313 - Converter - ERROR - Failed to push data to DB.
2025-03-07 12:51:43,313 - fastapi - INFO - Error in execution 'NoneType' object is not iterable
2025-03-07 12:51:43,313 - fastapi - INFO - Response: 200 | Time taken: 2.3625 sec
2025-03-07 13:10:13,764 - fastapi - INFO - User: Anonymous | Request: POST http://172.16.16.40:8000/uploading
2025-03-07 13:10:13,843 - fastapi - INFO - Received file '13.pdf' with provided password.
2025-03-07 13:10:13,843 - Converter - INFO - File Conversion START
2025-03-07 13:10:16,066 - Converter - INFO - File Conversion FINISH
2025-03-07 13:10:16,071 - Converter - ERROR - Error publishing JSON to DB, Exception: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "uq_folio_statement_period"
DETAIL:  Key (folio_number)=(1038436370 / 0) already exists.

[SQL: INSERT INTO folio (statement_period_id, folio_number, user_id, amc, pan) VALUES (%(statement_period_id)s, %(folio_number)s, %(user_id)s, %(amc)s, %(pan)s)]
[parameters: {'statement_period_id': 11, 'folio_number': '1038436370 / 0', 'user_id': 'ddba61f3-cde5-48bf-a3b2-4c364bd89855', 'amc': 'Aditya Birla Sun Life Mutual Fund', 'pan': 'AVYPR0077R'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "uq_folio_statement_period"
DETAIL:  Key (folio_number)=(1038436370 / 0) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/panda/mfa/financial-decision/routes/pdf_converter.py", line 222, in publish_json_to_db
    session.flush()
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4163, in flush
    self._flush(objects)
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4298, in _flush
    with util.safe_reraise():
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4259, in _flush
    flush_context.execute()
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1043, in _emit_insert_statements
    result = connection.execute(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/home/panda/mfa/financial-decision/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "uq_folio_statement_period"
DETAIL:  Key (folio_number)=(1038436370 / 0) already exists.

[SQL: INSERT INTO folio (statement_period_id, folio_number, user_id, amc, pan) VALUES (%(statement_period_id)s, %(folio_number)s, %(user_id)s, %(amc)s, %(pan)s)]
[parameters: {'statement_period_id': 11, 'folio_number': '1038436370 / 0', 'user_id': 'ddba61f3-cde5-48bf-a3b2-4c364bd89855', 'amc': 'Aditya Birla Sun Life Mutual Fund', 'pan': 'AVYPR0077R'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-03-07 13:10:16,071 - Converter - ERROR - Failed to push data to DB.
2025-03-07 13:10:16,071 - fastapi - INFO - Error in execution 'NoneType' object is not iterable
2025-03-07 13:10:16,072 - fastapi - INFO - Response: 200 | Time taken: 2.3077 sec
2025-03-07 13:31:29,837 - fastapi - INFO - PDF Converter initialized with custom progress handler
2025-03-07 13:31:29,846 - fastapi - INFO - Application started
2025-03-07 13:31:29,865 - fastapi - INFO - Application started
2025-03-07 13:37:29,179 - fastapi - INFO - PDF Converter initialized with custom progress handler
2025-03-07 13:37:29,187 - fastapi - INFO - Application started
2025-03-07 13:37:29,205 - fastapi - INFO - Application started
